repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.287  # Use the latest stable version of Ruff
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3
        types: [python]
        args: [--line-length=127]
  - repo: local
    hooks:
      - id: check-env-sync
        name: Check environment.yml sync with pyproject.toml
        entry: scripts/check_env_sync.py
        language: system # Assumes python is in the path, or use python
        types: [file]
        files: ^(pyproject\.toml|environment\.yml)$
