name: text-editor-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - flake8
  - black
  - pyyaml
  - tomli # For pyproject.toml parsing on Python < 3.11
  - pre-commit
  - pytest
  - pytest-xdist