name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Install OS dependencies (Node.js, Tkinter, Xvfb)
      run: |
        apt-get update -y && \
        apt-get install -y nodejs npm tk-dev tcl-dev xvfb
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install test dependencies (pytest, pytest-xdist)
      run: |
        echo "Pip for pytest install: $(which pip)"
        pip install pytest pytest-xdist
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo "CONDA PATH: $CONDA/bin" # Debugging $CONDA
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install Conda dependencies
      run: |
        conda env update --file environment.yml --name base
        echo "Python from Conda env update: $(which python)" # Debug which python conda uses
        echo "Pip from Conda env update: $(which pip)" # Debug which pip conda uses
    - name: Install project
      run: |
        echo "Python for pip install -e: $(which python)" # Debug which python is used for editable install
        pip install -e . -v
        echo "--- Installed packages after pip install -e . ---"
        pip list
        echo "--- PYTHONPATH after pip install -e . ---"
        echo "PYTHONPATH IS: $PYTHONPATH"
    - name: Test import before pytest
      run: |
        echo "Python for direct import test: $(which python)"
        # Test basic Tkinter functionality with Xvfb for early feedback
        xvfb-run python -c "import sys; print(f'Python sys.path: {sys.path}'); import editor; print('Successfully imported editor module'); import tkinter; root = tkinter.Tk(); print(f'Tkinter root: {root}'); root.destroy(); print('Successfully imported and initialized/destroyed tkinter root')"
    - name: Lint with flake8
      run: |
        # flake8 should be available from the conda env
        echo "Flake8 from: $(which flake8)"
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        echo "Pytest from module path: $(python -m pytest --version)" # Check if pytest module is found by this python
        echo "Python for pytest step: ${{ env.pythonLocation }}/bin/python"
        # Run pytest under Xvfb
        xvfb-run ${{ env.pythonLocation }}/bin/python -m pytest 